if: branch = master
language: node_js
node_js:
    - '13'
install:
    - npm install -g firebase-tools elm uglify-js
script:
    - elm make src/Main.elm --optimize --output public/main.js
    - uglifyjs public/main.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output=public/main.js
deploy:
    provider: firebase
    token:
        secure: "WEPpSx0yo37We9ZWdwHejUs2i/L1/B8EJRTtyrcYPF0ljsUn6k2pptpbh8tXwm7NzpUDcR+7TlIUjAVywwcKb4FlFI5WeqsF7mpv0//NXJ6SbyJzgd+NbWdRaDdVEbLSgmDneshUkbbUDWbBKTHoWK23+ajgE7gxk3NL00oDUVmZwt8e3+asg2IexPVQuVTCStxNjLBD1FLWsRpx2ojVeoyP2oGV4VBrkQwOvSnyG49UmPbOsOPDQj5YrDkoY+VK8UZGUNPgK37/dIUJ5cbJ9y/OyDBOtL/C8UgYYP0ZCODrOidCb7a/qP2yT0XJI55Z6wuzcQj8cgqofz9sWPDVjSmIcoURx4pu19aaLAf8cSegsBj/svIBP3lOcxI5pnloXUYBJvqqjBhEFOYV1DW3LTzBovTGcIpbE9wDVmxvSvpaqvrVPiYlVu32RIp9Kfq49IGlg92y1H3dvgEvUFxTU5/skr4zAg00bYUgcy4EDdPF4fHCkhodFkMWd3bkeMctEHknRaJoMwqfomDM2tIJuILe8mdgEON4eHC67WVslcuoUBFDjIAsXkPDJVEzKOZHz5ZZaufXM2VBUi8vgn8IfDfheM46AIRj4FPBLJ6IXk7gfmijfx/9KqcV+XbE/fd8dZrDUrU57lgwIWUuJQglnpTwj8g1ALunJPJvT6jv7jk="
    project: "echo-bedriftstur-81a2e"
    message: "Travis CI deploy"
