if: branch = master
language: node_js
node_js:
- '13'
install:
- npm install -g firebase-tools elm uglify-js
script:
- elm make src/Main.elm --optimize --output public/main.js
- uglifyjs public/main.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe'
  | uglifyjs --mangle --output=public/main.js
deploy:
  provider: firebase
  token:
    secure: SAW99a4sDGzYn5OsoumUCXJjD3u3acYHeSyIwAmzdJpjvl0DUxkp+QmJMxaxOwjYFh98Sf0ZMgPOzF9TGEaOYwcGxj3n4UJ1jCtMkxr+sMSjUeOSMKiSIG+DGu+S2iYLAZjPab311L2zNdAgcglfjBRfltuU0AOqcbvckt5nj6eYkie/PMkeVmkWZ6VzNfu1Ih3pi8AmvTE0FXu9bcqEQTEO9RP0/NuRdm4cAnVLU5cXQnvCNp+RENy1f7JxyrJTxqnueaJ8h2cb/9vP5+PPdJPZGGW82YHUwbUXR9KMCjYfd71bOr4xyqB2jq56V/I0uvwyToD7uQ/vGDE22rayypVgmFjJ85Cv65LXoYU7f6pr587wS2gfokYktzzsqTAqGcvEvefJ9uRwB5C2142qaa/UmDFWaJxDDCB96UCM7v1YJhth6oCmKuv8tfj/NeSNraaLB5BfXe/IZab7ow2Z1I9s92BJMlauYggf1DTMf3Xm9aQaIJSThcXRfWDNVrSBMEO7b8HP8GLKteogD3HTYa/U5fc79JE92hEHJEiLbwMPFt6RxpQdw+Ba6mTsvn0163UmPJbK928oCb3GZzyIq9zgJAfYrNeOhDGCQccIHrsdmsrC2up8dmlJ4ENfURw4tuhdbl1CW1KHN3wE14RXhcmtSskFbeFt778mEaBLsjg=
  message: Travis CI deploy
