name: Build, test & review

on:
  pull_request:
    branches: [master, develop]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-optional

      - name: Run tests
        run: yarn test

      - name: Run code review
        run: yarn review

      - name: Build
        run: yarn build
