name: Deploy prod

on:
  push:
    branches: master

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: prod-build
          path: public

  deploy:
    name: Deploy to prod site
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: prod-build
          path: public

      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.PROD_FIREBASE_TOKEN }}
          PROJECT_ID: echo-bedriftstur-81a2e
