name: Deploy from development branch

on:
  push:
    branches: develop

jobs:
  deploy:
    name: Deploy to development site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: dev-build
          path: dist
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:dev
        env:
          FIREBASE_TOKEN: ${{ secrets.DEV_FIREBASE_TOKEN }}
          PROJECT_ID: echo-bedriftstur-dev-60683
